package com.ngbj.browser2.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ngbj.browser2.bean.BigModelCountData;
import com.ngbj.browser2.bean.BookMarkData;
import com.ngbj.browser2.bean.CountData;
import com.ngbj.browser2.bean.HistoryData;
import com.ngbj.browser2.bean.KeyBean;
import com.ngbj.browser2.bean.ModelBean;
import com.ngbj.browser2.bean.StatisticsBean;
import com.ngbj.browser2.bean.UserInfoBean;
import com.ngbj.browser2.bean.WeatherSaveBean;

import com.ngbj.browser2.bean.BigModelCountDataDao;
import com.ngbj.browser2.bean.BookMarkDataDao;
import com.ngbj.browser2.bean.CountDataDao;
import com.ngbj.browser2.bean.HistoryDataDao;
import com.ngbj.browser2.bean.KeyBeanDao;
import com.ngbj.browser2.bean.ModelBeanDao;
import com.ngbj.browser2.bean.StatisticsBeanDao;
import com.ngbj.browser2.bean.UserInfoBeanDao;
import com.ngbj.browser2.bean.WeatherSaveBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bigModelCountDataDaoConfig;
    private final DaoConfig bookMarkDataDaoConfig;
    private final DaoConfig countDataDaoConfig;
    private final DaoConfig historyDataDaoConfig;
    private final DaoConfig keyBeanDaoConfig;
    private final DaoConfig modelBeanDaoConfig;
    private final DaoConfig statisticsBeanDaoConfig;
    private final DaoConfig userInfoBeanDaoConfig;
    private final DaoConfig weatherSaveBeanDaoConfig;

    private final BigModelCountDataDao bigModelCountDataDao;
    private final BookMarkDataDao bookMarkDataDao;
    private final CountDataDao countDataDao;
    private final HistoryDataDao historyDataDao;
    private final KeyBeanDao keyBeanDao;
    private final ModelBeanDao modelBeanDao;
    private final StatisticsBeanDao statisticsBeanDao;
    private final UserInfoBeanDao userInfoBeanDao;
    private final WeatherSaveBeanDao weatherSaveBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bigModelCountDataDaoConfig = daoConfigMap.get(BigModelCountDataDao.class).clone();
        bigModelCountDataDaoConfig.initIdentityScope(type);

        bookMarkDataDaoConfig = daoConfigMap.get(BookMarkDataDao.class).clone();
        bookMarkDataDaoConfig.initIdentityScope(type);

        countDataDaoConfig = daoConfigMap.get(CountDataDao.class).clone();
        countDataDaoConfig.initIdentityScope(type);

        historyDataDaoConfig = daoConfigMap.get(HistoryDataDao.class).clone();
        historyDataDaoConfig.initIdentityScope(type);

        keyBeanDaoConfig = daoConfigMap.get(KeyBeanDao.class).clone();
        keyBeanDaoConfig.initIdentityScope(type);

        modelBeanDaoConfig = daoConfigMap.get(ModelBeanDao.class).clone();
        modelBeanDaoConfig.initIdentityScope(type);

        statisticsBeanDaoConfig = daoConfigMap.get(StatisticsBeanDao.class).clone();
        statisticsBeanDaoConfig.initIdentityScope(type);

        userInfoBeanDaoConfig = daoConfigMap.get(UserInfoBeanDao.class).clone();
        userInfoBeanDaoConfig.initIdentityScope(type);

        weatherSaveBeanDaoConfig = daoConfigMap.get(WeatherSaveBeanDao.class).clone();
        weatherSaveBeanDaoConfig.initIdentityScope(type);

        bigModelCountDataDao = new BigModelCountDataDao(bigModelCountDataDaoConfig, this);
        bookMarkDataDao = new BookMarkDataDao(bookMarkDataDaoConfig, this);
        countDataDao = new CountDataDao(countDataDaoConfig, this);
        historyDataDao = new HistoryDataDao(historyDataDaoConfig, this);
        keyBeanDao = new KeyBeanDao(keyBeanDaoConfig, this);
        modelBeanDao = new ModelBeanDao(modelBeanDaoConfig, this);
        statisticsBeanDao = new StatisticsBeanDao(statisticsBeanDaoConfig, this);
        userInfoBeanDao = new UserInfoBeanDao(userInfoBeanDaoConfig, this);
        weatherSaveBeanDao = new WeatherSaveBeanDao(weatherSaveBeanDaoConfig, this);

        registerDao(BigModelCountData.class, bigModelCountDataDao);
        registerDao(BookMarkData.class, bookMarkDataDao);
        registerDao(CountData.class, countDataDao);
        registerDao(HistoryData.class, historyDataDao);
        registerDao(KeyBean.class, keyBeanDao);
        registerDao(ModelBean.class, modelBeanDao);
        registerDao(StatisticsBean.class, statisticsBeanDao);
        registerDao(UserInfoBean.class, userInfoBeanDao);
        registerDao(WeatherSaveBean.class, weatherSaveBeanDao);
    }
    
    public void clear() {
        bigModelCountDataDaoConfig.getIdentityScope().clear();
        bookMarkDataDaoConfig.getIdentityScope().clear();
        countDataDaoConfig.getIdentityScope().clear();
        historyDataDaoConfig.getIdentityScope().clear();
        keyBeanDaoConfig.getIdentityScope().clear();
        modelBeanDaoConfig.getIdentityScope().clear();
        statisticsBeanDaoConfig.getIdentityScope().clear();
        userInfoBeanDaoConfig.getIdentityScope().clear();
        weatherSaveBeanDaoConfig.getIdentityScope().clear();
    }

    public BigModelCountDataDao getBigModelCountDataDao() {
        return bigModelCountDataDao;
    }

    public BookMarkDataDao getBookMarkDataDao() {
        return bookMarkDataDao;
    }

    public CountDataDao getCountDataDao() {
        return countDataDao;
    }

    public HistoryDataDao getHistoryDataDao() {
        return historyDataDao;
    }

    public KeyBeanDao getKeyBeanDao() {
        return keyBeanDao;
    }

    public ModelBeanDao getModelBeanDao() {
        return modelBeanDao;
    }

    public StatisticsBeanDao getStatisticsBeanDao() {
        return statisticsBeanDao;
    }

    public UserInfoBeanDao getUserInfoBeanDao() {
        return userInfoBeanDao;
    }

    public WeatherSaveBeanDao getWeatherSaveBeanDao() {
        return weatherSaveBeanDao;
    }

}
